{{- if .Values.blueGreen.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}-svc-active
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
    service-type: active
  annotations:
    service.kubernetes.io/managed-by: "blue-green-deployment"
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
    version: {{ .Values.blueGreen.productionSlot }}
{{- end }}