{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
    {{- if .Values.serviceAccount.workloadIdentity.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
  annotations:
    {{- if .Values.serviceAccount.workloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.workloadIdentity.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.serviceAccount.workloadIdentity.tenantId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}